;----------------Definiciones e includes---------------------------------
.INCLUDE "m1280def.inc"     ;Incluir definiciones de registros para 1280
;----------------Inicializar---------------------------------------------
LDI R28,0X0CA					;YL = C0CA
LDI R29,0X0C0					;YH = B0B0
LDI	R30,0x0B0					;ZL = 1010 1010
LDI R31,0x0B0					;ZH = 0000 0000
LDI R24,1						;SELECT


;----------------Ciclo Principal-----------------------------------------

SETUPL:
	LDI R22,01					;MASCARAINICIO = 0000 0001
	LDI R23,128					;MASCARAFINAL = 1000 0000
	MOV R16,R28					;CARGAMOS EN DATA YL POR DEFAULT
	LDI R17,0						;CONTADOR
	CPI R24,1					;SI R24 = 1, EMPIEZA
	BREQ INICIO					;BRINCA A INICIO
	CPI R24,0					;VERIFICA SI R24 = 0
	BRNE FINAL					;SI NO, VA AL FINAL
	MOV R16,R30					;SI ES 0, USAMOS Z
INICIO:
	LDI R20,255					;CARGAMOS EL AUXILIAR CON 1'S
	PUSH R16					;GUARDAMOS EL REGISTRO DATA
	AND R16,R22					;CHECAMOS EL ESTADO DEL 1ER BIT
	BRNE NXT					;SI NO HAY 0'S NO SE HACEN CAMBIOS
INVIERTE:
	EOR R20,R23					;INVERTIMOS 1 BIT
NXT:
	CPI R22,0					;VERIFICAMOS SI LA MASCARA YA DIO LA VUELTA
	BREQ NXTBYTE				;SIGUIENTE BYTE
	POP R16						;RECUPERAMOS DATA
	PUSH R16					;GUARDAMOS DATA
	LSR R23						;RECORREMOS MASCRAFIN
	LSL R22						;RECORREMOS MASCARAINICIO
	AND R16,R22					;VERIFICAMOS BIT
	BRNE NXT					;SI NO HAY 0 NO HACEMOS CAMBIOS
	RJMP INVIERTE				;SI HAY 0 INVERTIMOS
NXTBYTE:
	POP R16						;SACAMOS EL DATO
	INC R17						;INCREMENTAMOS EL CONTADOR
	CPI R17,2					;COMPARAMOS CONTADOR CON 2
	BREQ ENDY					
	LDI	R22,01					;INICIALIZAMOS MASCARAINICIO
	LDI R23,128 				;INICIALIZAMOS MASCARAFIN
	CPI R24,1					;COMPARAMOS BANDERA EN R24
	BREQ SETUPH
	MOV R16,R31					;GUARDAMOS OLDZH
	MOV R31,R20					;ACTUALIZAMOS ZH
	RJMP INICIO
SETUPH:
	MOV R16,R29					;GUARDAMOS OLDYH
	MOV R29,R20					;ACTUALIZAMOS YH
	RJMP INICIO
ENDY:
	CPI R24,0					;CHECA BANDERA R24
	BREQ ENDZ					;SI UZAMOS Z SE VA A Z
	MOV R28,R20					;ACTUALIZA YL
	RJMP FINAL					;TERMINA
ENDZ:
	MOV R30,R20					;ACTUALIZA ZL
FINAL:
RJMP SETUPL
